# -*- coding: utf-8 -*-
"""SIMPLE NAME BOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ACSYi2K9JcDqbX0wloAL-qhH_qQfBLQ
"""

# Data types
# str = string = to write/keep text
print ('hello 8c')
# numeric types: integer (int), float (for decimals)
print ('8.5')

# math operator + - / % * addition, substraction, division, and multiplication
print ("8C+7C")

# VARIABLE + NAMING\
# in python + case sensitive
# ways on write variable = u're not allowed to start with number
# not put space between
#8c = 20 ---> wrong
# eight c = 20 ---> wrong
fried_fish = 100
fried_fish = 99

# input = determined the data type
name = input ("please type your name")
print ("name?")

name = input ("type ur name here")
age = input ("type ur age here")
print ("hi, name "you are ," age" years old" )